modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="dc_metro_mod"
version="1"
displayName="DC Metro Mod"
credits="Scriptivity Dev"
displayURL="https://scriptivity.tk"
logoFile="logo.png"
authors="Scriptivity"
description='''
Create amazing re creations of the DC metro using  Minecraft!
'''

[[dependencies.dc_metro_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




